export const LOGIN_HEADER = "Welcome back!"
export const LOGIN_SUBHEADER = "Please login to your account"
export const SIGN_IN = "Sign In"
export const FORGOT_PASSWORD = "Forgot password?"
export const SIGN_UP = "Don't have an account? Click to sign up"